<a href="https://colab.research.google.com/github/LSaldiasV/Mineria_de_Datos/blob/main/DataOngWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.options.display.max_rows = 9999
pd.options.display.max_columns = 9999

In [3]:
df = pd.read_csv("/content/DataONG.csv")

/tmp/ipykernel_26115/1908857065.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/DataONG.csv")

In [6]:
df.head(10)

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,MDMAUD,DOMAIN,CLUSTER,AGE,AGEFLAG,HOMEOWNR,CHILD03,CHILD07,CHILD12,CHILD18,NUMCHLD,INCOME,GENDER,WEALTH1,HIT,MBCRAFT,MBGARDEN,MBBOOKS,MBCOLECT,MAGFAML,MAGFEM,MAGMALE,PUBGARDN,PUBCULIN,PUBHLTH,PUBDOITY,PUBNEWFN,PUBPHOTO,PUBOPP,DATASRCE,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,STATEGOV,FEDGOV,SOLP3,SOLIH,MAJOR,WEALTH2,GEOCODE,COLLECT1,VETERANS,BIBLE,CATLG,HOMEE,PETS,CDPLAY,STEREO,PCOWNERS,PHOTO,CRAFTS,FISHER,GARDENIN,BOATS,WALKER,KIDSTUFF,CARDS,PLATES,LIFESRC,PEPSTRFL,POP901,POP902,POP903,POP90C1,POP90C2,POP90C3,POP90C4,POP90C5,ETH1,ETH2,ETH3,ETH4,ETH5,ETH6,ETH7,ETH8,ETH9,ETH10,ETH11,ETH12,ETH13,ETH14,ETH15,ETH16,AGE901,AGE902,AGE903,AGE904,AGE905,AGE906,AGE907,CHIL1,CHIL2,CHIL3,AGEC1,AGEC2,AGEC3,AGEC4,AGEC5,AGEC6,AGEC7,CHILC1,CHILC2,CHILC3,CHILC4,CHILC5,HHAGE1,HHAGE2,HHAGE3,HHN1,HHN2,HHN3,HHN4,HHN5,HHN6,MARR1,MARR2,MARR3,MARR4,HHP1,HHP2,DW1,DW2,DW3,DW4,DW5,DW6,DW7,DW8,DW9,HV1,HV2,HV3,HV4,HU1,HU2,HU3,HU4,HU5,HHD1,HHD2,HHD3,HHD4,HHD5,HHD6,HHD7,HHD8,HHD9,HHD10,HHD11,HHD12,ETHC1,ETHC2,ETHC3,ETHC4,ETHC5,ETHC6,HVP1,HVP2,HVP3,HVP4,HVP5,HVP6,HUR1,HUR2,RHP1,RHP2,RHP3,RHP4,HUPA1,HUPA2,HUPA3,HUPA4,HUPA5,HUPA6,HUPA7,RP1,RP2,RP3,RP4,MSA,ADI,DMA,IC1,IC2,IC3,IC4,IC5,IC6,IC7,IC8,IC9,IC10,IC11,IC12,IC13,IC14,IC15,IC16,IC17,IC18,IC19,IC20,IC21,IC22,IC23,HHAS1,HHAS2,HHAS3,HHAS4,MC1,MC2,MC3,TPE1,TPE2,TPE3,TPE4,TPE5,TPE6,TPE7,TPE8,TPE9,PEC1,PEC2,TPE10,TPE11,TPE12,TPE13,LFC1,LFC2,LFC3,LFC4,LFC5,LFC6,LFC7,LFC8,LFC9,LFC10,OCC1,OCC2,OCC3,OCC4,OCC5,OCC6,OCC7,OCC8,OCC9,OCC10,OCC11,OCC12,OCC13,EIC1,EIC2,EIC3,EIC4,EIC5,EIC6,EIC7,EIC8,EIC9,EIC10,EIC11,EIC12,EIC13,EIC14,EIC15,EIC16,OEDC1,OEDC2,OEDC3,OEDC4,OEDC5,OEDC6,OEDC7,EC1,EC2,EC3,EC4,EC5,EC6,EC7,EC8,SEC1,SEC2,SEC3,SEC4,SEC5,AFC1,AFC2,AFC3,AFC4,AFC5,AFC6,VC1,VC2,VC3,VC4,ANC1,ANC2,ANC3,ANC4,ANC5,ANC6,ANC7,ANC8,ANC9,ANC10,ANC11,ANC12,ANC13,ANC14,ANC15,POBC1,POBC2,LSC1,LSC2,LSC3,LSC4,VOC1,VOC2,VOC3,HC1,HC2,HC3,HC4,HC5,HC6,HC7,HC8,HC9,HC10,HC11,HC12,HC13,HC14,HC15,HC16,HC17,HC18,HC19,HC20,HC21,MHUC1,MHUC2,AC1,AC2,ADATE_2,ADATE_3,ADATE_4,ADATE_5,ADATE_6,ADATE_7,ADATE_8,ADATE_9,ADATE_10,ADATE_11,ADATE_12,ADATE_13,ADATE_14,ADATE_15,ADATE_16,ADATE_17,ADATE_18,ADATE_19,ADATE_20,ADATE_21,ADATE_22,ADATE_23,ADATE_24,RFA_2,RFA_3,RFA_4,RFA_5,RFA_6,RFA_7,RFA_8,RFA_9,RFA_10,RFA_11,RFA_12,RFA_13,RFA_14,RFA_15,RFA_16,RFA_17,RFA_18,RFA_19,RFA_20,RFA_21,RFA_22,RFA_23,RFA_24,CARDPROM,MAXADATE,NUMPROM,CARDPM12,NUMPRM12,RDATE_3,RDATE_4,RDATE_5,RDATE_6,RDATE_7,RDATE_8,RDATE_9,RDATE_10,RDATE_11,RDATE_12,RDATE_13,RDATE_14,RDATE_15,RDATE_16,RDATE_17,RDATE_18,RDATE_19,RDATE_20,RDATE_21,RDATE_22,RDATE_23,RDATE_24,RAMNT_3,RAMNT_4,RAMNT_5,RAMNT_6,RAMNT_7,RAMNT_8,RAMNT_9,RAMNT_10,RAMNT_11,RAMNT_12,RAMNT_13,RAMNT_14,RAMNT_15,RAMNT_16,RAMNT_17,RAMNT_18,RAMNT_19,RAMNT_20,RAMNT_21,RAMNT_22,RAMNT_23,RAMNT_24,RAMNTALL,NGIFTALL,CARDGIFT,MINRAMNT,MINRDATE,MAXRAMNT,MAXRDATE,LASTGIFT,LASTDATE,FISTDATE,NEXTDATE,TIMELAG,AVGGIFT,IDX,DONOR_FLAG,DONOR_AMOUNT,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,,,,XXXX,T2,36.0,60.0,,,,,,,NaN,NaN,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,39,34,18,10,2,1,NaN,NaN,,5.0,NaN,,,,,,,,,,,,,,,,,,,NaN,X,992,264,332,0,35,65,47,53,92,1,0,0,11,0,0,0,0,0,0,0,11,0,0,0,39,48,51,40,50,54,25,31,42,27,11,14,18,17,13,11,15,12,11,34,25,18,26,10,23,18,33,49,28,12,4,61,7,12,19,198,276,97,95,2,2,0,0,7,7,0,479,635,3,2,86,14,96,4,7,38,80,70,32,84,16,6,2,5,9,15,3,17,50,25,0,0,0,2,7,13,27,47,0,1,61,58,61,15,4,2,0,0,14,1,0,0,2,5,17,73,0.0,177.0,682.0,307,318,349,378,12883,13,23,23,23,15,1,0,0,1,4,25,24,26,17,2,0,0,2,28,4,51,1,46,54,3,88,8,0,0,0,0,0,0,4,1,13,14,16,2,45,56,64,50,64,44,62,53,99,0,0,9,3,8,13,9,0,3,9,3,15,19,5,4,3,0,3,41,1,0,7,13,6,5,0,4,9,4,1,3,10,2,1,7,78,2,0,120,16,10,39,21,8,4,3,5,20,3,19,4,0,0,0,18,39,0,34,23,18,16,1,4,0,23,0,0,5,1,0,0,0,0,0,2,0,3,74,88,8,0,4,96,77,19,13,31,5,14,14,31,54,46,0,0,90,0,10,0,0,0,33,65,40,99,99,6,2,10,7,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9508.0,9507.0,9506.0,9504.0,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,S4E,27,9702,74,6,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9512.0,NaN,NaN,NaN,9507.0,9505.0,9505.0,9503.0,NaN,NaN,NaN,NaN,NaN,9408.0,9406.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,10.0,11.0,11.0,11.0,NaN,NaN,NaN,NaN,NaN,11.0,9.0,240.0,31,14,5.0,9208,12.0,9402,10.0,9512,8911,9003.0,4.0,7.741935,95515,0,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,NWN,0,LA,70611,,,0,0,,,,,XXXX,T2,39.0,NaN,,U,,,,,NaN,2.0,F,9.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,34,36,12,3,3,1,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,,1485,424,512,99,0,0,51,49,96,2,0,1,2,0,0,0,0,0,0,0,1,0,0,1,28,37,39,30,39,43,32,36,42,23,14,28,26,16,10,4,2,15,14,36,21,14,10,3,9,15,29,56,33,11,3,69,9,3,20,227,289,63,62,0,16,16,9,0,0,0,702,787,3,3,76,24,96,4,5,54,83,71,44,93,7,9,2,7,13,7,3,26,64,7,1,1,0,1,6,18,39,85,0,2,46,53,55,16,5,8,8,21,6,7,8,3,8,13,61,91,3960.0,251.0,643.0,367,457,431,466,14248,13,14,21,17,26,3,7,0,0,8,14,22,15,29,4,8,0,0,12,3,32,4,46,54,7,80,17,0,0,0,0,0,2,1,1,9,21,23,5,76,79,89,69,85,65,75,66,85,0,2,12,12,5,11,17,0,1,10,0,18,4,1,10,0,10,7,23,9,3,5,15,1,4,1,0,11,6,3,3,3,3,1,2,87,3,0,120,4,3,49,20,3,17,5,1,35,2,27,7,0,0,0,17,34,0,36,48,12,12,0,2,11,4,0,0,7,1,0,0,0,0,0,3,0,0,81,95,1,0,4,99,70,22,5,15,0,5,31,77,92,8,0,0,44,1,55,0,0,0,99,0,19,99,98,7,2,9,4,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,9507.0,9506.0,NaN,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,NaN,9406.0,L3E,A3E,A3E,A3E,A3E,A3E,A3E,A3E,A2D,A2D,A2D,A2D,A1D,,N2D,N2D,N2D,N2D,N2D,N2D,N2D,,F1D,14,9702,35,6,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9508.0,9507.0,NaN,9504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,31.0,5,4,5.0,9507,11.0,9508,11.0,9508,9401,9407.0,6.0,6.200000,109359,0,0.0,1,L,3,E,X,X,X,38.0,C
2,9401,MSD,1,TN,37127-,,,3211,0,,,,,XXXX,T1,35.0,65.0,I,,,,,,NaN,NaN,M,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,28,51,14,5,2,2,NaN,NaN,,9.0,3.0,,,,,,,,,,,,,,,,,,,NaN,,2607,670,899,0,90,10,49,51,57,26,0,16,1,1,0,0,0,0,0,0,0,0,0,1,27,36,43,32,40,46,28,36,42,21,22,23,18,15,11,7,4,13,15,35,20,17,18,6,15,17,33,51,30,13,7,53,9,6,32,203,287,75,72,4,22,18,16,0,0,0,565,581,3,3,59,41,94,6,0,43,75,55,30,85,15,13,3,10,15,18,9,11,38,9,8,16,2,0,1,2,8,73,0,2,45,52,53,15,5,7,15,1,20,4,17,0,6,21,47,93,5360.0,181.0,659.0,291,329,311,332,10517,21,16,25,31,3,3,0,0,1,10,19,28,34,4,4,0,0,0,27,9,20,7,46,54,12,78,18,0,0,0,0,1,1,3,3,15,16,23,5,52,71,79,64,68,60,68,46,82,99,5,6,10,4,10,10,0,2,18,1,13,18,3,5,1,0,7,31,5,2,3,12,6,5,2,3,10,8,3,4,9,5,2,10,70,4,0,120,15,18,38,19,4,5,1,1,29,3,21,7,0,0,0,16,34,1,24,37,29,14,0,11,0,1,0,0,7,0,0,0,0,0,3,0,0,14,68,84,0,15,0,97,71,27,6,25,0,0,2,23,63,37,0,0,23,4,68,2,0,3,98,2,81,99,95,6,2,8,9,9706,9606.0,9604.0,NaN,9603.0,9602.0,9601.0,9511.0,9511.0,9511.0,9509.0,9507.0,NaN,NaN,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,NaN,NaN,L1F,A1F,A1F,,A1F,A1F,A1F,A1F,A1F,A1F,A1F,A1F,,,A1E,A1E,A1E,N2E,N2E,N2E,N2E,,,11,9702,28,4,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,3,1,3.0,9309,15.0,9504,15.0,9504,9309,9404.0,7.0,9.333333,49909,0,0.0,0,L,1,F,X,X,X,34.0,B
3,8901,ENQ,0,MN,56475,,,2603,0,,,,,XXXX,R3,51.0,72.0,,H,,,,,2.0,4.0,F,2.0,16,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,2,30,31,33,9,5,6,NaN,NaN,,0.0,NaN,,,,,,,,,,,,,,,,Y,,,1.0,X,1435,384,483,0,0,99,51,49,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,42,45,34,46,49,32,35,45,19,12,22,20,13,13,11,9,13,16,34,22,15,27,9,25,17,34,49,35,18,7,65,6,6,23,198,296,81,80,0,3,2,2,0,0,0,388,428,2,1,85,15,91,9,28,43,80,69,38,91,9,6,3,3,12,13,4,27,56,17,0,0,0,0,0,1,8,34,0,1,54,56,57,15,5,1,2,15,10,0,2,2,0,2,7,48,0.0,107.0,613.0,225,267,267,305,9587,31,23,21,15,8,1,1,0,0,22,23,24,18,11,1,1,0,0,34,8,47,13,30,70,1,64,15,0,0,0,0,0,6,16,0,11,14,21,6,52,65,72,58,68,53,71,71,76,92,4,9,6,2,9,12,0,0,12,17,15,8,6,4,18,0,8,16,4,1,2,16,2,4,2,1,7,7,4,7,9,4,6,17,54,7,2,120,20,10,40,12,10,6,1,2,26,1,24,3,1,2,0,16,30,1,31,20,33,14,0,1,1,21,0,0,1,0,2,11,0,0,0,2,0,0,89,97,1,0,2,96,66,23,13,34,0,6,12,37,47,53,0,0,1,30,6,40,0,23,37,62,40,98,95,7,2,6,7,9706,9606.0,9604.0,9604.0,9603.0,NaN,9601.0,9511.0,NaN,9510.0,9508.0,NaN,NaN,NaN,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,NaN,9406.0,L4D,S4D,S4D,S4D,S3D,,S2C,S2C,,L1D,L1D,,,,L1D,A1D,A1D,A1D,A1D,A1D,A1D,,A1D,21,9702,55,6,12,NaN,NaN,NaN,NaN,NaN,9601.0,NaN,NaN,NaN,9510.0,NaN,NaN,NaN,9507.0,NaN,NaN,NaN,9507.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,48.0,9,5,4.0,9507,7.0,9102,6.0,9601,8905,8910.0,5.0,5.333333,85548,0,0.0,1,L,4,D,X,X,X,57.0,D
4,9201,HCC,1,LA,70791,,,0,0,X,,,,XXXX,T2,40.0,NaN,,,,,,,NaN,NaN,M,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,27,37,28,10,10,1,NaN,12.0,,6.0,NaN,,,,,,,,,,,,,,,,,,,NaN,X,17649,4686,5741,51,1,48,49,51,68,31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,39,42,32,43,46,32,37,43,21,12,25,23,15,11,9,5,14,16,36,21,13,21,7,19,17,26,57,38,17,6,61,10,7,23,236,303,71,71,2,6,4,2,1,1,0,677,732,3,2,80,20,93,7,6,50,82,65,38,92,8,12,2,9,10,14,2,18,41,9,9,18,4,1,4,17,41,72,0,2,44,52,54,16,5,5,1,22,10,4,2,4,3,10,28,60,760.0,249.0,716.0,298,335,355,392,11556,26,17,15,17,16,5,1,1,1,20,17,16,19,19,6,2,1,1,26,9,31,15,32,68,4,81,13,0,0,0,0,0,2,3,1,19,24,27,4,71,61,74,50,68,46,55,38,63,69,12,11,10,4,9,17,0,3,9,2,18,6,4,5,2,0,8,18,3,8,3,14,4,4,2,1,9,9,5,9,10,10,1,5,69,5,0,120,9,16,36,21,4,11,4,3,28,2,24,4,0,0,0,13,27,1,37,14,30,9,0,4,3,3,0,0,7,1,0,0,0,0,0,0,0,0,78,97,0,0,2,93,64,20,8,17,1,12,32,59,77,23,0,1,50,4,40,1,0,4,99,1,55,99,95,9,2,5,5,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9508.0,9507.0,9506.0,9504.0,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L1G,A1G,A1G,A1G,A1G,S3G,S3G,S2G,S2G,S2G,S2G,S2G,S2G,S2G,S2G,A1F,A1F,A1F,S2F,S2F,S2F,S3F,S3F,23,9702,72,7,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9509.0,NaN,NaN,NaN,NaN,NaN,NaN,9411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,245.0,12,4,5.0,9211,50.0,9412,25.0,9612,9210,9211.0,1.0,20.416667,12890,0,0.0,0,L,1,G,X,X,X,38.0,B
5,9301,USB,1,UT,84720,,,2709,0,,,,,XXXX,T1,35.0,70.0,E,H,,,,,NaN,4.0,M,6.0,17,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,0.0,1.0,3.0,0,19,8,76,9,11,3,NaN,NaN,,6.0,NaN,,,,,,,,,,,,,,,,,,,NaN,,880,190,229,0,99,0,51,49,98,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,21,38,46,29,41,49,39,32,47,22,26,15,19,14,11,10,5,12,14,35,23,16,24,7,23,10,29,61,55,36,20,61,3,3,32,325,374,83,81,7,16,9,9,0,0,0,766,800,3,3,79,21,94,6,7,48,83,77,44,89,11,4,0,4,6,13,7,33,53,13,0,0,0,0,0,12,53,98,0,2,75,76,69,17,5,11,5,0,6,5,9,0,19,33,52,81,0.0,291.0,770.0,356,373,342,370,8424,12,17,19,30,22,0,0,0,0,5,9,30,33,22,0,0,0,0,27,0,43,11,42,58,13,82,7,0,0,0,0,2,7,2,0,5,8,12,2,15,60,69,48,69,45,72,56,99,0,0,19,6,4,19,12,0,4,18,3,5,0,9,2,5,1,2,4,3,6,6,22,5,3,9,4,3,17,5,7,9,11,3,9,61,5,1,154,0,4,14,26,9,31,15,0,48,2,25,20,0,0,0,11,19,0,8,31,76,0,0,49,0,6,0,0,1,0,0,0,0,0,1,0,0,0,81,96,1,2,1,99,88,41,12,17,6,14,30,53,74,26,0,0,37,0,15,38,0,10,99,0,99,99,96,6,2,4,8,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9509.0,9508.0,9507.0,9506.0,9504.0,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,9407.0,NaN,L1F,A1F,A1F,A1F,A2F,A3F,A3F,A3F,A3F,A3F,A3F,A2F,A3F,A3F,A2F,A2E,A2E,A2E,A2E,A2E,A2E,A2E,,18,9702,41,6,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9506.0,NaN,NaN,NaN,9502.0,9412.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,14.0,15.0,NaN,NaN,NaN,NaN,NaN,74.0,7,3,5.0,9306,15.0,9412,15.0,9506,9302,9306.0,4.0,10.571429,134891,0,0.0,1,L,1,F,X,X,X,37.0,D
6,9401,FRC,1,CA,90056,,,0,0,,,,,XXXX,U1,2.0,NaN,,H,,,,,NaN,1.0,M,9.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0,35,26,38,18,4,1,NaN,NaN,,NaN,5.0,,,,,,,,,,,,,,,,,,,NaN,,2539,725,1004,99,0,0,47,53,34,59,0,5,5,1,2,1,1,0,0,0,3,0,0,1,42,48,50,41,49,51,19,38,40,22,7,15,20,20,17,13,8,15,15,33,22,15,32,9,27,23,38,39,22,9,3,58,12,8,22,171,252,68,66,0,32,31,31,0,0,0,5251,5024,9,9,78,22,97,3,7,29,72,58,22,84,16,7,2,6,12,22,5,3,15,17,13,41,5,96,99,99,99,99,91,2,65,73,66,14,4,6,25,0,2,0,19,0,92,94,95,95,4480.0,13.0,803.0,681,806,740,865,36257,12,9,3,12,20,16,9,9,11,3,6,4,12,20,18,11,11,15,26,5,52,4,32,68,2,86,7,2,2,0,0,0,0,5,0,3,23,25,1,84,64,74,56,72,56,69,41,78,99,16,24,26,3,12,16,0,5,2,0,3,4,2,3,0,0,3,13,3,4,4,12,13,3,2,1,10,12,10,10,18,4,1,12,59,5,1,160,2,6,16,20,5,24,26,7,19,3,14,9,0,0,0,17,35,1,26,23,38,2,0,0,0,2,0,0,1,1,0,3,0,4,0,0,0,7,45,86,9,1,4,96,73,32,11,25,0,5,12,20,87,13,16,2,52,1,47,0,0,0,99,0,99,99,99,20,4,9,10,9706,9606.0,9604.0,NaN,9603.0,NaN,NaN,9511.0,9511.0,9509.0,9508.0,NaN,NaN,NaN,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,NaN,9406.0,L1F,A1F,A1F,,L1E,,,L1E,L1E,L1E,L1E,,,,L1E,N1E,N1E,N1E,N1E,N1E,N1E,,F1E,9,9702,27,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,2,1,10.0,9401,15.0,9512,15.0,9512,9401,9512.0,23.0,12.500000,143689,0,0.0,0,L,1,F,X,X,X,7.0,A
7,8801,PCH,2,IL,62376,,,5201,0,,,,,XXXX,R2,43.0,46.0,E,U,,,,,1.0,7.0,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0,30,35,27,4,4,3,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,,4429,1257,1593,0,0,99,49,51,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,44,47,37,47,50,28,38,39,23,10,20,21,14,13,11,11,14,16,33,23,14,28,12,26,20,35,46,29,12,3,69,5,9,17,187,272,86,85,0,2,2,1,2,2,0,342,377,2,1,80,20,85,15,45,38,79,71,33,89,11,5,1,4,8,16,1,23,56,21,0,0,0,0,0,2,6,20,0,1,57,57,59,14,4,2,1,10,14,2,1,3,0,0,2,25,0.0,227.0,717.0,245,283,280,313,10260,27,24,20,18,8,1,1,0,0,20,24,23,22,10,2,1,0,0,33,5,45,12,30,70,3,76,10,0,0,0,0,0,5,10,5,6,23,26,4,78,65,74,56,70,54,73,63,88,99,3,9,7,3,6,13,1,0,15,13,12,9,8,5,15,0,6,20,7,1,3,13,3,3,3,1,13,7,5,1,4,4,3,16,62,10,1,120,12,13,42,18,8,6,2,2,24,1,21,3,0,0,0,15,30,0,35,20,27,6,0,4,1,37,0,0,3,0,0,0,0,0,1,1,0,0,88,98,1,0,1,97,73,26,13,37,0,3,8,33,46,54,0,0,56,24,10,2,0,9,61,34,40,99,96,9,2,7,6,9706,9606.0,9604.0,9604.0,9603.0,NaN,NaN,9509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9501.0,9411.0,NaN,9410.0,9409.0,NaN,NaN,L1G,A1G,A1G,A1G,I3G,,,U1G,,,,,,,,,I1G,I1G,,I1G,I1G,,,19,9702,48,6,13,NaN,NaN,NaN,NaN,NaN,NaN,9512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,4,1,15.0,8906,45.0,9512,45.0,9512,8801,8906.0,17.0,25.000000,98090,0,0.0,0,L,1,G,X,X,X,56.0,C
8,8601,AMB,28,FL,32810,B,,3601,0,,,,,XXXX,S2,16.0,62.0,E,H,,,,,NaN,4.0,F,4.0,6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0,31,34,27,7,1,1,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,X,5614,1500,1943,99,0,0,48,52,79,15,1,2,12,0,0,0,0,0,1,0,1,8,1,2,28,36,38,30,41,44,31,47,36,17,14,33,21,11,9,8,5,20,18,32,16,14,18,5,14,16,30,53,31,12,5,57,14,5,24,215,287,72,70,2,21,19,16,0,0,0,661,668,4,4,65,35,95,5,8,48,77,57,32,86,14,16,3,13,13,15,6,19,49,11,6,9,1,0,0,2,22,91,0,4,46,52,52,16,5,9,12,7,14,5,16,1,24,52,76,83,5960.0,329.0,534.0,276,288,308,320,10859,25,19,22,19,13,2,0,0,1,23,19,22,19,15,2,0,0,1,20,8,26,14,55,45,17,74,21,1,1,0,0,1,2,3,0,25,21,25,4,71,74,79,70,73,66,72,44,81,58,11,7,9,3,12,18,1,2,15,0,16,7,6,3,1,1,10,12,3,4,4,26,6,7,3,7,5,3,5,3,7,1,1,6,80,4,0,120,8,13,37,24,8,9,2,2,23,2,19,4,0,0,0,14,31,0,34,11,27,23,0,4,1,7,0,0,4,2,0,0,0,0,1,0,0,7,37,85,11,1,3,91,62,16,4,15,0,13,40,55,71,29,1,0,12,2,75,9,0,1,94,6,51,99,95,7,2,3,5,9706,9606.0,9604.0,NaN,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,NaN,9506.0,NaN,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,NaN,NaN,L1F,A1F,A1F,,A1F,A1D,A1D,A1D,A1D,A1D,A1D,,A1D,,S2D,A1D,A1D,A1D,A1D,A1D,A1D,,,22,9702,50,4,11,NaN,NaN,NaN,NaN,NaN,NaN,9512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9412.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,81.0,10,6,5.0,8712,15.0,9512,15.0,9512,8702,8707.0,5.0,8.100000,35557,0,0.0,0,L,1,F,X,X,X,25.0,B
9,9501,L15,1,NC,27850,,,0,0,,,,,XXXX,C2,27.0,NaN,,,,,,,NaN,NaN,M,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,41,30,45,6,3,1,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,,5915,1723,2276,0,4,96,47,53,46,51,3,0,0,0,0,0,0,0,0,0,0,0,0,0,37,47,51,39,48,52,24,35,39,26,11,17,18,14,17,14,9,16,13,30,24,17,34,11,31,22,36,42,23,10,4,55,9,11,25,177,258,70,70,1,2,1,0,0,0,0,548,793,1,1,76,24,76,24,64,34,76,55,22,88,12,12,2,10,11,22,2,6,25,15,13,29,9,7,15,24,34,54,1,1,42,51,54,14,4,2,0,27,16,2,0,5,2,3,8,23,0.0,351.0,560.0,197,246,259,300,10044,40,19,16,12,8,2,1,1,0,31,20,18,15,10,2,2,1,0,38,16,26,25,30,70,8,72,19,1,1,0,0,0,6,2,5,21,21,24,4,66,55,63,48,59,43,63,41,36,96,27,11,5,2,10,12,2,3,8,5,10,17,6,7,5,0,8,32,2,3,2,16,2,3,4,1,5,8,3,4,5,10,1,9,70,4,0,120,21,23,27,13,5,8,3,3,20,1,17,4,0,0,0,14,31,1,19,20,46,9,0,10,0,3,0,0,6,1,0,0,0,0,1,0,0,0,83,98,1,0,1,85,53,21,10,22,4,13,26,51,69,31,0,0,4,16,27,31,0,21,30,68,19,91,89,8,2,8,10,9706,9606.0,9604.0,NaN,9603.0,9602.0,9601.0,9511.0,9510.0,9509.0,9508.0,9507.0,9506.0,NaN,9503.0,NaN,NaN,NaN,NaN,9409.0,9408.0,NaN,NaN,L1F,A1F,A1F,,A1F,N2F,N2F,N2F,N1F,N1F,N1F,N1F,F1F,,F1F,,,,,P1F,P1F,,,9,9702,24,4,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9507.0,NaN,NaN,NaN,NaN,NaN,NaN,9411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,30.0,2,1,15.0,9507,15.0,9411,15.0,9507,9411,9507.0,8.0,15.000000,42556,0,0.0,0,L,1,F,X,X,X,61.0,C

In [4]:
df.isna().sum()

ODATEDW             0
OSOURCE             0
TCODE               0
STATE               0
ZIP                 0
MAILCODE            0
PVASTATE            0
DOB                 0
NOEXCH              0
RECINHSE            0
RECP3               0
RECPGVG             0
RECSWEEP            0
MDMAUD              0
DOMAIN              0
CLUSTER          1141
AGE             11874
AGEFLAG             0
HOMEOWNR            0
CHILD03             0
CHILD07             0
CHILD12             0
CHILD18             0
NUMCHLD         41485
INCOME          10703
GENDER              0
WEALTH1         22350
HIT                 0
MBCRAFT         26410
MBGARDEN        26410
MBBOOKS         26410
MBCOLECT        26441
MAGFAML         26410
MAGFEM          26410
MAGMALE         26410
PUBGARDN        26410
PUBCULIN        26410
PUBHLTH         26410
PUBDOITY        26410
PUBNEWFN        26410
PUBPHOTO        26410
PUBOPP          26410
DATASRCE        10700
MALEMILI            0
MALEVET             0
VIETVETS            0
WWIIVETS            0
LOCALGOV            0
STATEGOV            0
FEDGOV              0
SOLP3           47643
SOLIH           44669
MAJOR               0
WEALTH2         21951
GEOCODE         40187
COLLECT1            0
VETERANS            0
BIBLE               0
CATLG               0
HOMEE               0
PETS                0
CDPLAY              0
STEREO              0
PCOWNERS            0
PHOTO               0
CRAFTS              0
FISHER              0
GARDENIN            0
BOATS               0
WALKER              0
KIDSTUFF            0
CARDS               0
PLATES              0
LIFESRC         27025
PEPSTRFL            0
POP901              0
POP902              0
POP903              0
POP90C1             0
POP90C2             0
POP90C3             0
POP90C4             0
POP90C5             0
ETH1                0
ETH2                0
ETH3                0
ETH4                0
ETH5                0
ETH6                0
ETH7                0
ETH8                0
ETH9                0
ETH10               0
ETH11               0
ETH12               0
ETH13               0
ETH14               0
ETH15               0
ETH16               0
AGE901              0
AGE902              0
AGE903              0
AGE904              0
AGE905              0
AGE906              0
AGE907              0
CHIL1               0
CHIL2               0
CHIL3               0
AGEC1               0
AGEC2               0
AGEC3               0
AGEC4               0
AGEC5               0
AGEC6               0
AGEC7               0
CHILC1              0
CHILC2              0
CHILC3              0
CHILC4              0
CHILC5              0
HHAGE1              0
HHAGE2              0
HHAGE3              0
HHN1                0
HHN2                0
HHN3                0
HHN4                0
HHN5                0
HHN6                0
MARR1               0
MARR2               0
MARR3               0
MARR4               0
HHP1                0
HHP2                0
DW1                 0
DW2                 0
DW3                 0
DW4                 0
DW5                 0
DW6                 0
DW7                 0
DW8                 0
DW9                 0
HV1                 0
HV2                 0
HV3                 0
HV4                 0
HU1                 0
HU2                 0
HU3                 0
HU4                 0
HU5                 0
HHD1                0
HHD2                0
HHD3                0
HHD4                0
HHD5                0
HHD6                0
HHD7                0
HHD8                0
HHD9                0
HHD10               0
HHD11               0
HHD12               0
ETHC1               0
ETHC2               0
ETHC3               0
ETHC4               0
ETHC5               0
ETHC6               0
HVP1                0
HVP2                0
HVP3                0
HVP4                0
HVP5                0
HVP6                0
HUR1                0
HUR2                0
RHP1                0
RHP2                0
RHP3                0
RHP4                0
HUPA1               0
HUPA2               0
HUPA3               0
HUPA4               0
HUPA5               0
HUPA6               0
HUPA7               0
RP1                 0
RP2                 0
RP3                 0
RP4                 0
MSA                46
ADI                46
DMA                46
IC1                 0
IC2                 0
IC3                 0
IC4                 0
IC5                 0
IC6                 0
IC7                 0
IC8                 0
IC9                 0
IC10                0
IC11                0
IC12                0
IC13                0
IC14                0
IC15                0
IC16                0
IC17                0
IC18                0
IC19                0
IC20                0
IC21                0
IC22                0
IC23                0
HHAS1               0
HHAS2               0
HHAS3               0
HHAS4               0
MC1                 0
MC2                 0
MC3                 0
TPE1                0
TPE2                0
TPE3                0
TPE4                0
TPE5                0
TPE6                0
TPE7                0
TPE8                0
TPE9                0
PEC1                0
PEC2                0
TPE10               0
TPE11               0
TPE12               0
TPE13               0
LFC1                0
LFC2                0
LFC3                0
LFC4                0
LFC5                0
LFC6                0
LFC7                0
LFC8                0
LFC9                0
LFC10               0
OCC1                0
OCC2                0
OCC3                0
OCC4                0
OCC5                0
OCC6                0
OCC7                0
OCC8                0
OCC9                0
OCC10               0
OCC11               0
OCC12               0
OCC13               0
EIC1                0
EIC2                0
EIC3                0
EIC4                0
EIC5                0
EIC6                0
EIC7                0
EIC8                0
EIC9                0
EIC10               0
EIC11               0
EIC12               0
EIC13               0
EIC14               0
EIC15               0
EIC16               0
OEDC1               0
OEDC2               0
OEDC3               0
OEDC4               0
OEDC5               0
OEDC6               0
OEDC7               0
EC1                 0
EC2                 0
EC3                 0
EC4                 0
EC5                 0
EC6                 0
EC7                 0
EC8                 0
SEC1                0
SEC2                0
SEC3                0
SEC4                0
SEC5                0
AFC1                0
AFC2                0
AFC3                0
AFC4                0
AFC5                0
AFC6                0
VC1                 0
VC2                 0
VC3                 0
VC4                 0
ANC1                0
ANC2                0
ANC3                0
ANC4                0
ANC5                0
ANC6                0
ANC7                0
ANC8                0
ANC9                0
ANC10               0
ANC11               0
ANC12               0
ANC13               0
ANC14               0
ANC15               0
POBC1               0
POBC2               0
LSC1                0
LSC2                0
LSC3                0
LSC4                0
VOC1                0
VOC2                0
VOC3                0
HC1                 0
HC2                 0
HC3                 0
HC4                 0
HC5                 0
HC6                 0
HC7                 0
HC8                 0
HC9                 0
HC10                0
HC11                0
HC12                0
HC13                0
HC14                0
HC15                0
HC16                0
HC17                0
HC18                0
HC19                0
HC20                0
HC21                0
MHUC1               0
MHUC2               0
AC1                 0
AC2                 0
ADATE_2             0
ADATE_3           970
ADATE_4          1087
ADATE_5         16768
ADATE_6          1785
ADATE_7          4398
ADATE_8          1770
ADATE_9          5672
ADATE_10        16370
ADATE_11         5170
ADATE_12         4423
ADATE_13        20122
ADATE_14         9515
ADATE_15        32795
ADATE_16        10245
ADATE_17        13729
ADATE_18        10592
ADATE_19        12241
ADATE_20        25100
ADATE_21        17569
ADATE_22        12746
ADATE_23        28149
ADATE_24        18504
RFA_2               0
RFA_3               0
RFA_4               0
RFA_5               0
RFA_6               0
RFA_7               0
RFA_8               0
RFA_9               0
RFA_10              0
RFA_11              0
RFA_12              0
RFA_13              0
RFA_14              0
RFA_15              0
RFA_16              0
RFA_17              0
RFA_18              0
RFA_19              0
RFA_20              0
RFA_21              0
RFA_22              0
RFA_23              0
RFA_24              0
CARDPROM            0
MAXADATE            0
NUMPROM             0
CARDPM12            0
NUMPRM12            0
RDATE_3         47604
RDATE_4         47591
RDATE_5         47718
RDATE_6         47339
RDATE_7         43284
RDATE_8         36971
RDATE_9         39359
RDATE_10        42489
RDATE_11        40316
RDATE_12        34812
RDATE_13        41614
RDATE_14        36157
RDATE_15        44067
RDATE_16        34284
RDATE_17        42991
RDATE_18        37791
RDATE_19        39802
RDATE_20        43816
RDATE_21        43021
RDATE_22        37142
RDATE_23        43814
RDATE_24        38807
RAMNT_3         47604
RAMNT_4         47591
RAMNT_5         47718
RAMNT_6         47339
RAMNT_7         43284
RAMNT_8         36971
RAMNT_9         39359
RAMNT_10        42489
RAMNT_11        40316
RAMNT_12        34812
RAMNT_13        41614
RAMNT_14        36157
RAMNT_15        44067
RAMNT_16        34284
RAMNT_17        42991
RAMNT_18        37791
RAMNT_19        39802
RAMNT_20        43816
RAMNT_21        43021
RAMNT_22        37142
RAMNT_23        43814
RAMNT_24        38807
RAMNTALL            0
NGIFTALL            0
CARDGIFT            0
MINRAMNT            0
MINRDATE            0
MAXRAMNT            0
MAXRDATE            0
LASTGIFT            0
LASTDATE            0
FISTDATE            0
NEXTDATE         5017
TIMELAG          5017
AVGGIFT             0
IDX                 0
DONOR_FLAG          0
DONOR_AMOUNT        0
HPHONE_D            0
RFA_2R              0
RFA_2F              0
RFA_2A              0
MDMAUD_R            0
MDMAUD_F            0
MDMAUD_A            0
CLUSTER2           46
GEOCODE2           46
dtype: int64

In [5]:
df.tail(10)

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,MDMAUD,DOMAIN,CLUSTER,AGE,AGEFLAG,HOMEOWNR,CHILD03,CHILD07,CHILD12,CHILD18,NUMCHLD,INCOME,GENDER,WEALTH1,HIT,MBCRAFT,MBGARDEN,MBBOOKS,MBCOLECT,MAGFAML,MAGFEM,MAGMALE,PUBGARDN,PUBCULIN,PUBHLTH,PUBDOITY,PUBNEWFN,PUBPHOTO,PUBOPP,DATASRCE,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,STATEGOV,FEDGOV,SOLP3,SOLIH,MAJOR,WEALTH2,GEOCODE,COLLECT1,VETERANS,BIBLE,CATLG,HOMEE,PETS,CDPLAY,STEREO,PCOWNERS,PHOTO,CRAFTS,FISHER,GARDENIN,BOATS,WALKER,KIDSTUFF,CARDS,PLATES,LIFESRC,PEPSTRFL,POP901,POP902,POP903,POP90C1,POP90C2,POP90C3,POP90C4,POP90C5,ETH1,ETH2,ETH3,ETH4,ETH5,ETH6,ETH7,ETH8,ETH9,ETH10,ETH11,ETH12,ETH13,ETH14,ETH15,ETH16,AGE901,AGE902,AGE903,AGE904,AGE905,AGE906,AGE907,CHIL1,CHIL2,CHIL3,AGEC1,AGEC2,AGEC3,AGEC4,AGEC5,AGEC6,AGEC7,CHILC1,CHILC2,CHILC3,CHILC4,CHILC5,HHAGE1,HHAGE2,HHAGE3,HHN1,HHN2,HHN3,HHN4,HHN5,HHN6,MARR1,MARR2,MARR3,MARR4,HHP1,HHP2,DW1,DW2,DW3,DW4,DW5,DW6,DW7,DW8,DW9,HV1,HV2,HV3,HV4,HU1,HU2,HU3,HU4,HU5,HHD1,HHD2,HHD3,HHD4,HHD5,HHD6,HHD7,HHD8,HHD9,HHD10,HHD11,HHD12,ETHC1,ETHC2,ETHC3,ETHC4,ETHC5,ETHC6,HVP1,HVP2,HVP3,HVP4,HVP5,HVP6,HUR1,HUR2,RHP1,RHP2,RHP3,RHP4,HUPA1,HUPA2,HUPA3,HUPA4,HUPA5,HUPA6,HUPA7,RP1,RP2,RP3,RP4,MSA,ADI,DMA,IC1,IC2,IC3,IC4,IC5,IC6,IC7,IC8,IC9,IC10,IC11,IC12,IC13,IC14,IC15,IC16,IC17,IC18,IC19,IC20,IC21,IC22,IC23,HHAS1,HHAS2,HHAS3,HHAS4,MC1,MC2,MC3,TPE1,TPE2,TPE3,TPE4,TPE5,TPE6,TPE7,TPE8,TPE9,PEC1,PEC2,TPE10,TPE11,TPE12,TPE13,LFC1,LFC2,LFC3,LFC4,LFC5,LFC6,LFC7,LFC8,LFC9,LFC10,OCC1,OCC2,OCC3,OCC4,OCC5,OCC6,OCC7,OCC8,OCC9,OCC10,OCC11,OCC12,OCC13,EIC1,EIC2,EIC3,EIC4,EIC5,EIC6,EIC7,EIC8,EIC9,EIC10,EIC11,EIC12,EIC13,EIC14,EIC15,EIC16,OEDC1,OEDC2,OEDC3,OEDC4,OEDC5,OEDC6,OEDC7,EC1,EC2,EC3,EC4,EC5,EC6,EC7,EC8,SEC1,SEC2,SEC3,SEC4,SEC5,AFC1,AFC2,AFC3,AFC4,AFC5,AFC6,VC1,VC2,VC3,VC4,ANC1,ANC2,ANC3,ANC4,ANC5,ANC6,ANC7,ANC8,ANC9,ANC10,ANC11,ANC12,ANC13,ANC14,ANC15,POBC1,POBC2,LSC1,LSC2,LSC3,LSC4,VOC1,VOC2,VOC3,HC1,HC2,HC3,HC4,HC5,HC6,HC7,HC8,HC9,HC10,HC11,HC12,HC13,HC14,HC15,HC16,HC17,HC18,HC19,HC20,HC21,MHUC1,MHUC2,AC1,AC2,ADATE_2,ADATE_3,ADATE_4,ADATE_5,ADATE_6,ADATE_7,ADATE_8,ADATE_9,ADATE_10,ADATE_11,ADATE_12,ADATE_13,ADATE_14,ADATE_15,ADATE_16,ADATE_17,ADATE_18,ADATE_19,ADATE_20,ADATE_21,ADATE_22,ADATE_23,ADATE_24,RFA_2,RFA_3,RFA_4,RFA_5,RFA_6,RFA_7,RFA_8,RFA_9,RFA_10,RFA_11,RFA_12,RFA_13,RFA_14,RFA_15,RFA_16,RFA_17,RFA_18,RFA_19,RFA_20,RFA_21,RFA_22,RFA_23,RFA_24,CARDPROM,MAXADATE,NUMPROM,CARDPM12,NUMPRM12,RDATE_3,RDATE_4,RDATE_5,RDATE_6,RDATE_7,RDATE_8,RDATE_9,RDATE_10,RDATE_11,RDATE_12,RDATE_13,RDATE_14,RDATE_15,RDATE_16,RDATE_17,RDATE_18,RDATE_19,RDATE_20,RDATE_21,RDATE_22,RDATE_23,RDATE_24,RAMNT_3,RAMNT_4,RAMNT_5,RAMNT_6,RAMNT_7,RAMNT_8,RAMNT_9,RAMNT_10,RAMNT_11,RAMNT_12,RAMNT_13,RAMNT_14,RAMNT_15,RAMNT_16,RAMNT_17,RAMNT_18,RAMNT_19,RAMNT_20,RAMNT_21,RAMNT_22,RAMNT_23,RAMNT_24,RAMNTALL,NGIFTALL,CARDGIFT,MINRAMNT,MINRDATE,MAXRAMNT,MAXRDATE,LASTGIFT,LASTDATE,FISTDATE,NEXTDATE,TIMELAG,AVGGIFT,IDX,DONOR_FLAG,DONOR_AMOUNT,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
47710,8601,STR,0,WI,53223,,,1110,0,,,,,XXXX,S1,11.0,86.0,I,,,,,,NaN,NaN,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32,21,26,9,1,0,NaN,NaN,,9.0,NaN,,,,,,,,,,,,,,,,,,,NaN,,2368,651,930,99,0,0,50,50,85,12,0,3,1,1,0,1,1,0,0,0,1,0,0,1,36,42,45,37,44,47,21,34,39,27,12,21,21,19,14,9,4,16,13,28,24,19,18,5,16,26,33,41,25,10,4,61,7,4,28,172,254,69,65,0,30,30,29,0,0,0,934,975,5,5,75,25,98,2,10,29,70,64,27,85,15,3,1,2,16,17,4,14,57,14,2,9,1,1,2,37,86,99,0,3,58,61,57,14,4,7,24,0,2,1,22,0,30,94,97,97,5080.0,111.0,617.0,476,529,511,562,20261,6,9,16,21,31,12,3,1,1,2,8,17,18,34,15,4,1,1,25,2,74,1,32,68,5,87,8,0,0,0,0,0,2,2,1,18,20,22,2,67,75,80,70,78,69,83,60,89,0,3,25,9,4,13,11,0,3,7,0,14,8,3,3,1,1,3,23,2,2,5,19,5,7,1,2,8,12,6,2,9,1,0,5,76,9,0,140,4,4,27,23,8,20,14,5,20,0,15,9,0,1,0,16,32,0,21,26,26,5,0,1,0,34,1,0,1,1,0,1,0,0,0,0,0,5,72,92,1,3,4,98,72,24,9,19,0,1,13,53,89,11,12,7,79,0,18,2,0,0,99,0,99,99,99,8,4,8,5,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,9507.0,9506.0,9504.0,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L3G,A3G,A3G,A3G,A2G,A1F,A1F,A1F,A1F,A1F,A1F,A1F,A2F,A2F,A3F,A2F,A2F,A2F,A2F,A2F,A2F,A1F,A1F,29,9702,71,6,16,NaN,NaN,NaN,NaN,NaN,9602.0,NaN,9511.0,9511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9412.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,10.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,144.0,10,4,5.0,8906,25.0,9511,20.0,9602,8711,8902.0,15.0,14.400000,78831,1,3.0,0,L,3,G,X,X,X,3.0,B
47711,8601,ROA,0,GA,30736,,,5410,0,,,,,XXXX,T2,36.0,43.0,,H,,,,,NaN,2.0,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0,28,41,22,5,4,3,NaN,NaN,,1.0,NaN,,,Y,Y,,,,Y,,,,,Y,,,,,,2.0,,1038,314,394,0,0,99,49,51,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,42,45,36,45,48,25,32,41,27,13,20,23,16,13,10,6,14,13,33,26,14,24,8,21,18,36,45,24,9,3,68,10,6,16,187,263,78,77,2,6,5,0,0,0,0,539,700,3,3,80,20,95,5,9,37,80,69,31,90,10,7,2,5,10,15,2,20,63,16,0,0,0,4,8,18,29,55,1,1,46,53,55,14,4,6,0,14,9,6,0,5,5,7,26,79,1560.0,199.0,575.0,287,340,361,408,14484,32,15,13,13,17,6,0,0,4,23,15,15,15,20,7,0,0,5,34,4,31,14,34,66,10,71,21,0,0,0,0,0,2,6,34,21,19,22,0,77,59,68,52,65,47,51,68,0,99,7,17,14,3,4,20,0,0,10,2,13,10,5,2,4,0,13,28,12,0,2,5,6,2,0,0,6,14,7,2,8,8,2,12,62,7,0,120,23,16,26,11,3,13,9,2,24,2,19,5,0,0,0,11,23,0,30,8,20,13,0,11,0,5,0,0,13,1,0,0,0,0,0,0,0,0,55,99,1,0,0,89,67,19,8,23,2,20,34,52,76,24,0,0,25,6,55,6,0,9,90,10,12,99,94,6,1,8,5,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,9507.0,9506.0,9504.0,9503.0,9502.0,9412.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L3G,A3G,A3G,A3G,A3G,A3G,A3G,A3G,A2G,A2G,A2G,A2G,A1G,A1G,A1G,A2G,A2G,A2G,A2G,A2G,A2G,A3G,A3G,33,9702,72,6,16,NaN,NaN,NaN,NaN,NaN,NaN,9601.0,NaN,NaN,NaN,NaN,9507.0,NaN,9505.0,NaN,NaN,NaN,NaN,9502.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,30.0,NaN,50.0,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN,276.0,17,9,5.0,9101,50.0,9505,25.0,9601,8612,8809.0,21.0,16.235294,29549,0,0.0,0,L,3,G,X,X,X,38.0,B
47712,8801,DNA,2,FL,33157,,,1201,0,,,,,XXXX,S2,20.0,86.0,E,H,,,,,NaN,4.0,F,9.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2,37,36,32,11,1,6,NaN,NaN,,9.0,NaN,,,,,,,,,,,,,,,,,,,NaN,,5296,1335,1970,99,0,0,45,55,92,5,0,2,14,0,0,1,0,0,0,0,1,2,6,5,38,46,49,40,50,53,24,38,42,20,9,18,21,15,11,10,18,16,15,36,20,13,40,24,36,29,28,43,26,11,3,57,9,14,19,174,255,73,70,1,26,25,18,5,5,0,977,1180,5,5,71,29,96,4,2,33,68,58,28,80,20,5,1,4,10,27,3,18,50,24,1,3,1,9,16,46,94,99,1,18,59,62,54,14,5,11,15,0,7,6,16,0,49,50,53,62,5000.0,127.0,528.0,458,513,486,568,20791,19,10,7,20,25,13,2,1,3,7,8,7,25,30,15,2,1,4,39,2,54,7,42,58,13,82,10,2,0,1,0,0,3,3,2,3,28,30,7,73,59,73,48,70,46,65,51,99,99,0,14,17,6,14,19,1,6,6,1,13,1,0,1,2,0,8,3,8,7,6,14,9,6,2,2,8,7,7,10,11,1,6,7,67,7,0,136,6,9,25,26,8,18,8,5,20,1,17,7,1,2,0,17,37,1,36,19,32,15,1,8,0,8,0,0,7,2,0,1,0,1,1,0,0,10,27,85,11,1,4,82,55,20,6,22,2,9,11,44,88,12,2,1,21,1,74,0,0,0,99,0,91,99,99,10,3,5,6,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,NaN,9506.0,NaN,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L1F,A2F,A2F,A2F,A2F,A1E,A1E,A1E,A1E,A1E,A1E,,A1E,,L1F,L2F,L2F,A1F,A1F,A1F,A1F,A1F,A1F,27,9702,65,6,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9511.0,NaN,NaN,NaN,NaN,NaN,9503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,8,5,10.0,9503,15.0,8809,15.0,9511,8809,9101.0,28.0,12.125000,38061,0,0.0,1,L,1,F,X,X,X,4.0,A
47713,9401,HHH,28,LA,70806,,,2801,0,,,,,XXXX,C1,24.0,70.0,E,H,,,,,NaN,6.0,F,8.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0,33,33,47,5,14,0,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,,1523,457,730,99,0,0,44,56,97,3,0,0,2,0,0,0,0,0,0,0,0,0,0,1,42,48,51,43,50,52,16,41,37,22,8,19,17,13,16,15,11,15,19,30,18,18,35,15,34,34,41,25,12,4,1,57,13,11,19,139,209,64,62,0,35,35,26,0,0,0,922,1244,4,4,65,35,93,7,0,20,63,49,14,80,20,6,1,5,11,33,3,13,55,29,1,2,0,12,18,39,74,94,7,3,51,57,57,12,3,15,20,0,8,8,18,0,12,43,81,95,760.0,249.0,716.0,342,410,408,485,24775,17,19,16,23,16,4,0,1,5,8,20,13,25,21,4,0,1,7,35,1,53,2,42,58,11,92,6,0,0,0,0,0,1,2,1,7,15,19,5,48,65,70,61,68,58,93,69,99,99,0,30,18,3,16,15,0,0,8,0,7,1,0,1,0,0,4,7,2,4,3,10,14,3,3,0,15,13,15,6,5,14,0,10,61,10,0,143,4,5,18,29,5,23,15,6,14,1,10,10,0,0,0,15,33,0,33,13,47,3,1,11,5,5,0,0,5,7,0,0,0,1,1,0,0,1,67,92,3,0,5,95,63,19,6,25,1,6,22,34,68,32,10,9,55,0,45,0,0,0,99,0,99,99,99,7,2,7,9,9706,9606.0,9604.0,NaN,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,NaN,9506.0,NaN,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,NaN,9406.0,L1F,A1F,A1F,,A1F,A1D,A1D,A1D,A1D,A1D,A1D,,A1D,,A1D,N1D,N1D,N1D,N1D,N1D,N1D,,F1D,11,9702,30,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,29.0,3,0,5.0,9312,15.0,9511,15.0,9511,9312,9410.0,10.0,9.666667,109741,0,0.0,1,L,1,F,X,X,X,32.0,B
47714,9501,HOS,0,AL,35653,,,0,0,,,,,XXXX,R3,51.0,NaN,,,,,,,NaN,NaN,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,20,21,63,7,8,7,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,,938,266,318,0,84,16,49,51,96,2,0,1,0,0,0,0,1,0,0,0,0,0,0,0,34,42,47,36,45,49,25,38,41,21,14,19,20,19,11,9,9,14,18,32,23,13,19,8,16,15,30,55,29,8,2,66,8,9,17,220,280,96,95,0,0,0,0,5,5,0,457,522,2,2,80,20,93,7,0,43,84,74,38,88,12,5,0,4,8,13,2,19,60,16,1,1,0,0,0,4,18,46,0,1,55,55,58,16,4,0,0,3,19,0,0,2,0,11,22,41,0.0,185.0,691.0,263,276,333,342,10803,30,17,13,20,13,4,0,2,0,28,18,12,21,14,5,0,2,0,22,5,23,14,44,56,4,77,19,0,0,0,0,0,4,0,3,37,17,22,4,54,66,76,57,71,53,66,58,54,0,10,10,11,4,15,18,0,2,9,1,12,8,3,6,0,0,3,18,4,7,4,22,5,3,1,1,11,7,7,8,7,8,7,7,65,5,2,120,12,22,32,18,2,7,8,3,18,1,18,1,0,0,0,10,20,0,21,29,63,0,0,8,0,4,0,0,11,0,0,0,0,0,1,0,0,1,82,96,1,3,0,90,67,35,9,19,2,9,20,64,82,18,0,0,48,0,42,0,0,11,99,0,54,99,93,5,2,5,4,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9509.0,9507.0,9506.0,NaN,NaN,9501.0,9412.0,NaN,NaN,NaN,NaN,NaN,NaN,L3E,A3E,A3E,A3E,N4E,N3E,N3E,N2E,N2E,N2E,N2E,N2E,N2E,,,P1A,P1D,,,,,,,11,9702,27,6,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9512.0,NaN,NaN,9509.0,NaN,NaN,NaN,NaN,9501.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,39.0,4,2,8.0,9501,11.0,9512,11.0,9512,9501,9503.0,2.0,9.750000,47945,0,0.0,0,L,3,E,X,X,X,53.0,D
47715,9001,LHJ,0,MN,55932,,,4001,0,,,,,XXXX,R2,49.0,58.0,E,H,,,,,NaN,4.0,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0,24,46,20,6,1,2,NaN,NaN,,5.0,NaN,,,,,,,,,,,,,,,,,,,NaN,X,1663,450,581,0,1,99,50,50,99,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,40,43,33,44,47,32,37,43,20,13,24,23,13,10,8,9,13,17,33,24,12,23,11,23,20,30,51,34,15,4,68,5,6,20,205,286,81,81,2,10,9,7,0,0,0,585,606,3,2,79,21,97,3,13,45,77,70,40,90,10,6,1,4,12,12,3,28,57,15,0,0,0,0,0,8,25,62,0,1,65,64,63,15,4,7,4,8,9,3,7,2,0,2,23,82,0.0,107.0,613.0,281,342,326,376,11157,27,16,17,22,12,4,1,0,0,14,18,19,26,15,5,2,0,0,23,2,46,9,38,62,4,69,15,0,0,0,0,0,4,12,0,53,22,23,1,71,71,78,63,75,62,78,66,79,95,3,9,5,7,10,15,1,2,13,15,12,6,4,3,16,0,6,12,5,1,11,12,3,4,3,1,18,4,4,2,6,1,2,17,59,13,2,120,12,9,45,12,9,11,2,2,29,3,24,4,0,0,0,13,25,1,43,19,21,8,0,1,0,44,0,0,3,0,6,0,0,0,0,1,0,0,85,97,1,0,2,97,75,27,9,28,3,10,17,40,50,50,0,0,35,28,11,16,0,10,51,48,46,99,97,7,4,5,6,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9509.0,9508.0,9507.0,9506.0,9504.0,9503.0,NaN,NaN,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L1F,A1F,A1F,A1F,L3F,A2F,A2F,A2F,A3F,A3F,A3F,A3F,A3F,A3F,A3F,,,A3F,A2F,A2F,A2F,A3F,A3F,22,9702,51,4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9412.0,NaN,NaN,9408.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN,20.0,NaN,139.0,12,6,3.0,9003,20.0,9312,20.0,9601,9003,9101.0,10.0,11.583333,84678,1,10.0,0,L,1,F,X,X,X,56.0,D
47716,9401,L02,2,KY,41701-,,,4506,0,,,,,XXXX,R2,43.0,53.0,E,H,,,,,1.0,1.0,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0,24,31,28,9,9,2,NaN,NaN,,3.0,NaN,,,Y,,,Y,Y,Y,Y,,,,Y,,,,,,3.0,X,10214,2850,3516,0,17,83,49,51,98,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31,39,43,34,43,47,28,32,43,24,16,22,22,14,11,9,6,12,14,33,24,17,22,8,20,18,27,55,31,12,4,60,9,9,21,220,286,65,64,1,8,7,5,1,1,0,341,421,2,1,76,24,92,8,3,47,81,64,36,91,9,10,2,8,9,17,1,23,60,15,1,1,0,1,2,5,13,31,0,2,36,49,52,16,5,7,2,26,11,3,4,5,1,3,8,32,0.0,211.0,541.0,159,185,214,236,7542,48,18,12,15,6,1,0,0,0,42,18,14,17,6,1,0,0,0,30,15,16,34,32,68,3,78,15,1,0,0,0,0,4,3,0,13,18,23,5,59,46,59,33,49,30,34,22,43,63,25,9,7,3,15,13,1,2,11,1,16,3,14,4,0,18,6,4,5,4,3,25,2,4,3,0,7,10,3,6,8,9,2,5,70,5,1,118,30,21,30,10,2,3,3,1,26,1,21,4,0,0,0,11,23,1,32,22,29,10,0,5,1,3,0,0,7,1,0,0,0,0,1,0,0,0,89,99,0,0,0,83,47,14,8,17,2,13,30,59,68,32,0,0,21,4,49,2,0,23,44,45,34,94,85,8,3,5,6,9706,9606.0,9604.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9508.0,9507.0,9506.0,9504.0,9503.0,9502.0,9501.0,9411.0,NaN,9410.0,9409.0,9407.0,9406.0,L4E,S4E,S4E,S4E,S4E,S3E,S3E,S4E,S4D,S4D,S4D,S4D,S4D,S4D,S4D,S4D,S4D,N4D,,N3D,N3D,N3D,N2C,17,9702,38,6,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9510.0,NaN,9508.0,9506.0,9504.0,NaN,NaN,NaN,NaN,NaN,9410.0,9407.0,9407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,11.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,59.0,10,8,3.0,9401,11.0,9508,8.0,9510,9310,9401.0,3.0,5.900000,58178,0,0.0,0,L,4,E,X,X,X,53.0,D
47717,9001,LHJ,0,FL,32776-,,,4803,0,,,,,XXXX,S2,16.0,50.0,E,H,,,,,NaN,6.0,F,6.0,10,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,3.0,2,44,26,46,25,9,1,NaN,NaN,,6.0,NaN,,,,,,,,,,,,,,,,,,,NaN,X,1834,529,628,0,0,99,49,51,88,8,1,1,3,0,0,0,0,1,0,0,2,0,0,1,38,45,47,38,46,49,22,35,39,25,9,20,20,19,15,12,5,15,14,31,24,16,24,5,21,12,43,46,25,10,4,66,10,6,18,190,273,59,58,1,1,0,0,6,0,6,733,875,4,3,87,13,90,10,25,35,84,74,30,85,15,6,2,4,9,12,4,15,56,17,2,4,2,6,10,23,47,87,0,1,47,53,55,14,4,1,0,40,7,1,0,4,13,36,67,75,5960.0,329.0,534.0,285,288,333,334,11390,23,21,15,24,13,1,3,0,0,20,23,16,23,14,2,1,0,0,31,1,37,17,44,56,7,66,17,0,0,0,0,0,14,3,1,48,24,30,10,69,67,78,57,75,50,72,55,99,99,0,8,17,0,9,17,3,1,14,9,9,7,4,2,22,0,10,13,3,3,5,15,4,8,3,3,3,3,2,3,4,2,2,6,83,3,0,120,10,25,27,19,9,8,2,3,21,2,17,5,0,0,0,21,40,2,37,18,41,5,0,10,1,8,0,0,4,1,0,2,0,0,0,0,0,5,41,95,2,0,3,97,72,33,9,13,6,18,44,83,92,8,0,0,0,29,69,1,0,0,0,99,0,99,99,6,1,5,8,9706,9606.0,9604.0,NaN,9603.0,9602.0,9601.0,9511.0,NaN,9510.0,9508.0,NaN,9506.0,NaN,9503.0,NaN,9501.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L4D,S4D,S4D,,S4D,S3D,S3D,S2D,,S2D,S2D,,S2D,,S2C,,S3C,S3C,S3C,S3C,S3C,S3C,S3C,23,9702,59,5,12,NaN,NaN,NaN,NaN,9602.0,NaN,NaN,NaN,NaN,9510.0,NaN,9506.0,NaN,NaN,NaN,9501.0,NaN,NaN,NaN,NaN,NaN,9406.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,3.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,3.0,81.0,24,12,2.0,9602,9.0,9103,2.0,9602,9003,9006.0,3.0,3.375000,35088,0,0.0,0,L,4,D,X,X,X,43.0,C
47718,9501,MBC,1,MI,48910,,,3801,0,,X,,,XXXX,C3,30.0,60.0,,,,,,,NaN,NaN,M,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,18,46,20,7,23,0,NaN,NaN,,NaN,NaN,,,,,,,,,,,,,,,,,,,NaN,X,552,131,205,99,0,0,53,47,82,14,0,1,9,0,0,0,0,0,0,0,9,0,0,0,28,35,37,30,41,44,32,46,38,17,13,34,21,9,9,9,4,21,17,32,20,10,18,7,17,27,29,44,31,14,5,45,19,5,31,179,268,96,95,1,2,1,0,0,0,0,376,377,4,3,66,34,95,5,10,37,64,43,21,80,20,16,2,14,21,20,9,20,49,12,7,7,1,0,0,0,1,9,0,2,45,51,54,14,5,2,0,0,31,2,0,0,3,34,78,91,4040.0,61.0,551.0,263,264,319,345,12178,21,26,20,18,12,0,3,0,0,26,18,17,11,21,0,6,0,0,10,13,26,26,43,57,3,83,17,0,0,0,0,0,0,0,0,25,17,17,0,69,69,70,69,70,69,77,24,62,0,25,5,13,9,5,22,0,2,14,0,13,9,5,2,0,0,4,14,3,11,0,10,5,2,0,5,6,19,3,19,7,23,0,0,52,18,0,120,5,3,51,23,7,11,0,6,32,4,27,7,0,0,0,9,18,0,46,0,20,20,2,8,0,14,0,0,0,1,0,0,0,0,1,0,0,6,82,92,5,3,0,93,42,12,6,51,0,0,0,0,0,99,0,0,97,0,0,0,0,4,99,0,99,99,99,5,2,3,11,9706,9606.0,9604.0,9604.0,9603.0,NaN,9601.0,9511.0,9510.0,9510.0,9509.0,9507.0,9506.0,9504.0,9503.0,NaN,9501.0,NaN,NaN,9409.0,9408.0,NaN,NaN,L3E,S4E,S4E,S3E,S3E,,A2E,N3E,N3E,N3E,N3E,N3E,N3E,N2E,F1D,,F1D,,,P1D,P1D,,,14,9702,33,7,17,NaN,NaN,NaN,NaN,NaN,9601.0,NaN,NaN,NaN,9510.0,NaN,NaN,NaN,NaN,NaN,9501.0,NaN,NaN,NaN,9410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,5.0,NaN,NaN,58.0,7,4,3.0,9603,10.0,9501,10.0,9610,9410,9501.0,3.0,8.285714,189641,0,0.0,1,L,3,E,X,X,X,34.0,B
47719,8601,PRV,0,CA,91320,,,4005,0,X,,,,XXXX,C1,24.0,58.0,E,H,,,,,NaN,7.0,F,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0,28,35,20,9,1,1,NaN,12.0,,7.0,4.0,,,,,,,,,,,,,,,,,,,1.0,X,1746,432,508,99,0,0,47,53,92,1,1,5,8,0,1,2,0,1,0,0,5,0,0,3,34,42,45,36,45,49,25,38,40,22,12,21,21,18,12,7,9,13,16,34,20,17,20,4,16,9,26,65,41,17,6,56,9,8,27,262,324,99,99,0,0,0,0,5,4,1,2421,2459,11,10,88,12,99,1,0,44,85,71,36,84,16,8,2,6,9,12,6,19,56,16,0,0,0,89,96,99,99,99,9,0,90,65,68,18,5,0,0,0,12,0,0,0,88,88,90,91,8735.0,13.0,803.0,552,544,568,556,15948,7,4,11,18,38,15,5,3,0,4,6,15,19,38,13,4,3,0,25,2,46,3,43,57,9,80,11,0,0,0,0,1,2,6,0,24,18,28,11,52,73,88,60,85,57,70,54,99,99,0,14,16,6,16,17,0,2,12,1,11,2,0,2,1,0,2,22,4,6,4,19,4,7,2,4,6,7,9,4,9,1,1,7,72,8,2,140,7,6,20,35,12,15,5,6,29,4,21,10,0,0,0,13,28,1,35,18,20,8,0,3,1,9,0,0,2,6,1,2,0,0,0,0,0,14,50,83,8,4,5,99,85,43,9,25,0,0,6,17,99,1,0,0,99,0,1,0,0,0,99,0,99,99,99,12,3,6,3,9706,9606.0,9609.0,9604.0,9603.0,9602.0,9601.0,9511.0,9510.0,9510.0,9508.0,9507.0,9506.0,9504.0,9503.0,9502.0,9501.0,9411.0,9411.0,9410.0,9409.0,9407.0,9406.0,L4F,S4F,A3F,S4F,S4F,S4F,S4F,S4F,S4F,S4F,S4F,S4F,S4F,S4F,S3F,S2F,S2F,A1F,A1F,A1F,A1F,S2F,S3F,36,9702,127,9,31,NaN,9608.0,NaN,NaN,NaN,NaN,NaN,9512.0,9511.0,NaN,9508.0,NaN,9507.0,9506.0,NaN,9502.0,NaN,NaN,9501.0,9410.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,18.0,18.0,NaN,20.0,NaN,18.0,18.0,NaN,15.0,NaN,NaN,15.0,20.0,NaN,NaN,498.0,41,18,5.0,9011,21.0,9608,18.0,9701,8612,8704.0,4.0,12.146341,4693,1,18.0,1,L,4,F,X,X,X,11.0,A

In [8]:
df.shape

(47720, 481)

In [10]:
conteo_df_original = df.shape[0]

In [11]:
df_limpio = df.dropna()

In [12]:
conteo_df_limpio = df_limpio.shape[0]

In [13]:
print(f"Filas de datos original: {conteo_df_original}")
print(f"Filas de datos limpios: {conteo_df_limpio}")

Filas de datos original: 47720
Filas de datos limpios: 0

In [15]:
df.isnull().any().any()

np.True_

In [17]:
df_limpio.isnull().any().any()

np.False_

In [18]:
# Agrupación de las columnas por tipo de datos
tipos = df.columns.to_series().groupby(df.dtypes).groups
# Conociendo la lista de columnas categóricas
ctext = tipos[np.dtype('object')]
len(ctext) # cantidad de columnas con datos categóricos.

68

In [19]:
# Agrupación de las columnas por tipo de datos
tipos = df_limpio.columns.to_series().groupby(df_limpio.dtypes).groups
# Conociendo la lista de columnas categóricas
ctext = tipos[np.dtype('object')]
len(ctext) # cantidad de columnas con datos categóricos.

68

In [20]:
columnas = df.columns
cnum = list(set(columnas) - set(ctext))
print(len(cnum))

413

In [21]:
columnas = df_limpio.columns
cnum = list(set(columnas) - set(ctext))
len(cnum)

413

In [22]:
# Completando valores faltantes datos cuantititavos
for columna in cnum:
  mean = df[columna].mean()
  df[columna] = df[columna].fillna(mean)

In [25]:
for columna in ctext:
  mode = df[columna].mode()[0]
  df[columna] = df[columna].fillna(mode)

In [27]:
df.isnull().any().any()

np.False_